### ISSUE TITLE
Don't attempt to translate icon name

### ISSUE THREAD

**Issue by ratijas** [najepaliya/kleaner#2]
https://github.com/najepaliya/kleaner/blob/0fa60dca9fd07c829019c5468359206e075add6f/src/contents/ui/HomePage.qml#L228C5-L228C56

icon name should not be wrapped in i18n call.

Actually there is a concept of internationalization for graphic resources like images and icons (especially RTL variants), but it is done differently and not in simple case like this :)

https://developer.apple.com/design/human-interface-guidelines/sf-symbols#Design-variants

**Comment by najepaliya** [comment]
This is the first thing I fixed on my end lol how does it keep coming back? Damn you Kate .swp files

**Comment by najepaliya** [comment]
Fixed.
